locale: "de-DE"
title: Mr. T's Geschnippeltes-Geschnappeltes...
baseurl: "/mr-t.org"
url: "https://taitruong.github.io"
google_analytics_key: ""

# Default description in social shares for the jekyll-seo-tag gem
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# Author details for the jekyll-seo-tag gem
author:
  name: Mr. T
  email: me@mr-t.org
  twitter: TajMyTai

# Social details for the jekyll-seo-tag gem
social:
  name: Mr. T, mamaskitchen.de, software-developer.org
  links:
    - https://github.com/taitruong/mr-t.org

permalink: pretty

gems:
  - "jekyll-feed"
  - "jekyll-seo-tag"
  - "jekyll-paginate"
  - "jekyll-sitemap"

# Jekyll SEO Tag
webmaster_verifications:
  google: # 1234
  bing: # 1234
  alexa: # 1234
  yandex: # 1234

# -----------
# CloudCannon

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - RSS
